name: SpigotAPI
version: 1.0.0
main: net.xilla.spigotcore.SpigotAPI
description: A gems plugin
author: Tobias
softdepend: [PlaceholderAPI]
load: STARTUP
commands:
  spigotcore:
    usage: /<command>
    permission: spigotcore.admin
    description: "Spigot core command"